// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sqnyrjdmrvhjqlnlacfm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNxbnlyamRtcnZoanFsbmxhY2ZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyOTk1NjUsImV4cCI6MjA2NTg3NTU2NX0.ufUDoYMQM9U76FQ0SrBa2Bqs0NtLPu4p497taI-3pLk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});